# 1.0.0.0 - 02 Dec 2021
name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '4.7.2'
    - run: echo '${{ steps.stepid.outputs.dotnet-version }}' # outputs 3.1.422
    - name: Build PreciseManeuver
      run: dotnet build  ./source/PreciseManeuver.csproj